//CONSTANSTS FOR ACTION TYPES

//RULE ACTION TYPES
const BLACKJACK_RULES_OPEN   = "BLACKJACK_RULES_OPEN";
const BLACKJACK_RULES_CLOSED = "BLACKJACK_RULES_CLOSED";
const CASINO_RULES_OPEN      = "CASINO_RULES_OPEN";
const CASINO_RULES_CLOSED    = "CASINO_RULES_CLOSED";

//GAME PROGRESS ACTION TYPES
const ROUND_FINISHED       = "ROUND_FINISHED";
const ROUND_STARTED        = "ROUND_STARTED";
const PLAYER_TURN_STARTED  = "PLAYER_TURN_STARTED";
const PLAYER_TURN_FINISHED = "PLAYER_TURN_FINISHED";
const DEALER_TURN_STARTED  = "DEALER_TURN_STARTED";
const DEALER_TURN_FINISHED = "DEALER_TURN_FINISHED";

//GAME ACTION TYPES
const DEALER_START = "DEALER_START";
const DEALER_HIT   = "DEALER_HIT";
const PLAYER_START = "PLAYER_START";
const PLAYER_HIT   = "PLAYER_HIT";

export { BLACKJACK_RULES_OPEN, BLACKJACK_RULES_CLOSED,
         CASINO_RULES_OPEN, CASINO_RULES_CLOSED,
         ROUND_FINISHED, ROUND_STARTED, PLAYER_TURN_STARTED,
         PLAYER_TURN_FINISHED, DEALER_TURN_STARTED, DEALER_TURN_FINISHED,
         DEALER_START, DEALER_HIT, PLAYER_START, PLAYER_HIT
        }
