//CONSTANSTS FOR ACTION TYPES

const BLACKJACK_RULES_OPEN   = "BLACKJACK_RULES_OPEN";
const BLACKJACK_RULES_CLOSED = "BLACKJACK_RULES_CLOSED";
const CASINO_RULES_OPEN      = "CASINO_RULES_OPEN";
const CASINO_RULES_CLOSED    = "CASINO_RULES_CLOSED";

export { BLACKJACK_RULES_OPEN, BLACKJACK_RULES_CLOSED,
         CASINO_RULES_OPEN, CASINO_RULES_CLOSED }
