//CONSTANSTS FOR ACTION TYPES

//RULE ACTION TYPES
const BLACKJACK_RULES_OPEN   = "BLACKJACK_RULES_OPEN";
const BLACKJACK_RULES_CLOSED = "BLACKJACK_RULES_CLOSED";
const CASINO_RULES_OPEN      = "CASINO_RULES_OPEN";
const CASINO_RULES_CLOSED    = "CASINO_RULES_CLOSED";

//GAME PROGRESS ACTION TYPES
const ROUND_FINISHED       = "ROUND_FINISHED";
const ROUND_STARTED        = "ROUND_STARTED";
const PLAYER_TURN_STARTED  = "PLAYER_TURN_STARTED";
const PLAYER_TURN_FINISHED = "PLAYER_TURN_FINISHED";
const PLAYER_SPLIT_TURN_STARTED = "PLAYER_SPLIT_TURN_STARTED";
const PLAYER_SPLIT_TURN_FINISHED = "PLAYER_SPLIT_TURN_FINISHED";
const DEALER_TURN_STARTED  = "DEALER_TURN_STARTED";
const DEALER_TURN_FINISHED = "DEALER_TURN_FINISHED";
const PAYOUT_STARTED       = "PAYOUT_STARTED";
const PAYOUT_FINISHED      = "PAYOUT_FINISHED";

//GAME ACTION TYPES
const DEALER_START       = "DEALER_START";
const DEALER_REVEAL      = "DEALER_REVEAL";
const DEALER_HIT         = "DEALER_HIT";
const PLAYER_START       = "PLAYER_START";
const PLAYER_HIT         = "PLAYER_HIT";
const SET_PLAYER_CHIPS   = "SET_PLAYER_CHIPS";
const SET_CURRENT_BET    = "SET_CURRENT_BET";
const SET_PLAYER_CARDS   = "SET_PLAYER_CARDS";
const SET_COMP_ONE_CARDS = "SET_COMP_ONE_CARDS";
const SET_COMP_TWO_CARDS = "SET_COMP_TWO_CARDS";
const SET_DEALER_CARDS   = "SET_DEALER_CARDS";

//COMPUTER PLAYER ACTION TYPES
const COMP_ONE_TURN_STARTED    = "COMP_ONE_TURN_STARTED";
const COMP_ONE_TURN_FINISHED   = "COMP_ONE_TURN_FINISHED";
const COMP_TWO_TURN_STARTED    = "COMP_TWO_TURN_STARTED";
const COMP_TWO_TURN_FINISHED   = "COMP_TWO_TURN_FINISHED";
const COMP_ONE_START           = "COMP_ONE_START";
const COMP_TWO_START           = "COMP_TWO_START";
const COMP_ONE_HIT             = "COMP_ONE_HIT";
const COMP_TWO_HIT             = "COMP_TWO_HIT";

//SPLIT ACTION TYPES
const SET_PLAYER_SPLIT_CARDS   = "SET_PLAYER_SPLIT_CARDS";
const PLAYER_SPLIT_FINISHED    = "PLAYER_SPLIT_FINISHED";

//DOUBLE ACTION TYPES
const PLAYER_DOUBLED       = "PLAYER_DOUBLED";
const RESET_PLAYER_DOUBLED = "RESET_PLAYER_DOUBLED";

export { BLACKJACK_RULES_OPEN, BLACKJACK_RULES_CLOSED,
         CASINO_RULES_OPEN, CASINO_RULES_CLOSED,
         PAYOUT_STARTED, PAYOUT_FINISHED,
         ROUND_FINISHED, ROUND_STARTED, PLAYER_TURN_STARTED,
         PLAYER_SPLIT_TURN_STARTED,
         PLAYER_SPLIT_TURN_FINISHED,
         PLAYER_TURN_FINISHED, DEALER_TURN_STARTED, DEALER_TURN_FINISHED,
         DEALER_START, DEALER_REVEAL, DEALER_HIT, PLAYER_START, PLAYER_HIT,
         SET_PLAYER_CHIPS, SET_CURRENT_BET,
         COMP_ONE_TURN_STARTED, COMP_TWO_TURN_STARTED, COMP_ONE_TURN_FINISHED, COMP_TWO_TURN_FINISHED,
         COMP_ONE_START, COMP_TWO_START, COMP_ONE_HIT, COMP_TWO_HIT,
         PLAYER_SPLIT_STARTED, PLAYER_SPLIT_HIT, PLAYER_SPLIT_FINISHED,
         SET_PLAYER_CARDS, SET_PLAYER_SPLIT_CARDS,
         PLAYER_DOUBLED, RESET_PLAYER_DOUBLED,
         SET_COMP_ONE_CARDS, SET_COMP_TWO_CARDS, SET_DEALER_CARDS,
        }
